In [1]:
import numpy as np
import scipy as sp
from numpy import math
%pylab
%matplotlib inline

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


# Repaso de Archivos

In [2]:
#Archivo de escritura
arch=open("datos.txt","w")
arch.write("Creado por Álvaro López Zamora \n")
arch.close()

In [3]:
#Archivo con append (agregar información a un archivo existente)
arch2=open("datos.txt","a")
arch2.write("Margarita Olmedo de la Peña \n")
arch2.close()

# Arreglos

In [10]:
np.random.randint(10,99) #Genera numeros enteros aleatorioes entre los limites que nosotros pongamos

66

In [11]:
arrA=np.random.randint(10,99,(5,7)) #Los últiimos números especifican la cantidad de renglones y columnas
arrA

array([[93, 25, 21, 56, 95, 48, 37],
       [47, 95, 63, 52, 83, 76, 96],
       [44, 94, 52, 65, 73, 63, 30],
       [50, 88, 34, 12, 40, 72, 59],
       [55, 90, 53, 46, 76, 53, 74]])

In [9]:
arrA.ndim

2

In [44]:
arrA.size

35

In [45]:
arrA.shape

(5, 7)

In [51]:
arrB=np.random.randint(10,99,(4,5,7))
arrB

array([[[72, 21, 85, 51, 75, 21, 58],
        [57, 76, 54, 19, 41, 57, 21],
        [33, 40, 48, 47, 54, 40, 82],
        [41, 41, 40, 16, 10, 14, 91],
        [21, 80, 90, 15, 64, 52, 15]],

       [[18, 67, 58, 79, 74, 72, 90],
        [19, 59, 55, 73, 90, 60, 21],
        [23, 70, 55, 68, 44, 86, 86],
        [20, 30, 17, 69, 58, 53, 20],
        [51, 39, 18, 15, 51, 42, 71]],

       [[40, 81, 11, 46, 50, 91, 34],
        [46, 62, 20, 80, 64, 40, 43],
        [49, 27, 10, 73, 73, 48, 97],
        [61, 70, 20, 39, 89, 56, 67],
        [22, 81, 44, 54, 54, 14, 63]],

       [[25, 46, 61, 37, 78, 38, 83],
        [95, 57, 88, 93, 29, 88, 91],
        [86, 61, 82, 16, 90, 41, 23],
        [63, 40, 18, 18, 54, 77, 91],
        [91, 14, 29, 44, 92, 85, 40]]])

In [52]:
arrB.ndim

3

In [15]:

arrA[4,5] #especificamos las coordenadas (índice) 

53

In [27]:
arrA[:2] #Dame todo el primer renglon

array([[93, 25, 21, 56, 95, 48, 37],
       [47, 95, 63, 52, 83, 76, 96]])

In [29]:
arreglito=arrA[1:3,3:6] #los primeros 4 elementos de los primeros 3 renglones. Extrae una sección
arreglito

array([[52, 83, 76],
       [65, 73, 63]])

In [31]:
arrA[0,4]

95

In [32]:
#Convertimos un arreglo multidimensional en matriz
matA=np.mat(arrA)
matA

matrix([[93, 25, 21, 56, 95, 48, 37],
        [47, 95, 63, 52, 83, 76, 96],
        [44, 94, 52, 65, 73, 63, 30],
        [50, 88, 34, 12, 40, 72, 59],
        [55, 90, 53, 46, 76, 53, 74]])

In [41]:
#Problema de los caramelos
mC=np.mat("5 2;8 3") #matrix que representa las cajas compradas
mP=np.mat("68;104")

In [42]:
mC

matrix([[5, 2],
        [8, 3]])

In [43]:
mP

matrix([[ 68],
        [104]])

In [44]:
mC.I  #saca la matriz inversa de la matriz original

matrix([[-3.,  2.],
        [ 8., -5.]])

In [71]:
solucion=(mC.I)*(mP) #El valor de cada caja se obtiene multiplicando la matriz inversa por la matriz de precios
solucion

matrix([[ 4.],
        [24.]])

In [73]:
# Por lo tanto Pagué 4 pesos por caja de caramelos y 24 por caja de chocolates 

In [76]:
matrizIdentidad=(mC.I)*(mC)
matrizIdentidad

matrix([[1., 0.],
        [0., 1.]])

Veamos que podemos resolver el mismo problema utilizando la biblioteca de algebra lineal de numpy

In [80]:
np.linalg.solve(mC,mP)

matrix([[ 4.],
        [24.]])

## Ejercicios Arreglos y Matrices

In [45]:
#Sistema de ecuaciones 2
mV=np.mat("1 1 1;2 -1 -1;1 -3 2") #matrix que representa las cajas compradas
mS=np.mat("6;-3;5")

In [46]:
solucion=np.linalg.solve(mV,mS)
solucion

matrix([[1. ],
        [1.2],
        [3.8]])

In [ ]:
Integrantes:
    Sara Olivares
    Armando Hernández
    Ricardo Illescas
    David Hernández
    Sebastian Abascal
    Álvaro López